name: jgspdx
favicon: null
layout_spectrum: 0.07004732522182167
typography_spectrum: 0.05410318006761372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4501006167847663
  lightness: 0.48226292454637587
  saturation: 0.3533512547146529
  rhythmicContrast: 0.8584280156064779
purpose: []
